### ISSUE TITLE
Parser Extension: p.letters('hello')=>'hello'

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/parsec#12]
Letters is a succession of letters

**Comment by nicolas-zozol** [comment]
A strange thing is that `P.letters('some Letters')` is accepted, but the values is stopped at `'some'`. In my opinion it should be rejected.

**Comment by d-plaindoux** [comment]
This is normal because P.letters('some letter') only consumes the substring some. ' letter' should be consumed by some different parsers. Therefor `P.letters().then(P.char(' ')).then(P.letters()) should consume 'some letter'.

**Comment by nicolas-zozol** [comment]
I used `parser.letters.then(parser.eos)` to ensure I have only letters.
