### ISSUE TITLE
How to select up to a given sequence?

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/parsec#18]
What is the proper way to select everything up to a given sequence?

Let's say that I have this source : `"wordSTOPwordagainSTOP"`
And I want my value to be : `["word","wordagain"]`

I have wrote : 

```
function stop(){
    return P.string('STOP').rep();
}
function detectStop(){
    return P.try(stop().or(P.letters())).rep();
}
function parseText( line, offset=0){
    return detectStop().parse(stream.ofString(line), offset)
}
```
So once the parser enters into letters(), it does not come back to see if there is a STOP, which has however a better priority. How would I do that ?

====

But suppose that the separator is now `-stop-` with not only letters

function stop(){
    return P.string('-stop-').rep();
}

And we test : `test-stop-test-stop-`, then my parser works

It is easy, because the parse will detect a special character '-'. But we don't  always want to 
introduce a special character.

====

**Comment by nicolas-zozol** [comment]
I think we've got it, reading what @d-plaindoux made on [markdown separator](https://github.com/d-plaindoux/parsec/blob/master/src/lib/standard/markdown.js#L52)  :)

```
function stop(){
    return P.string('STOP').rep();
}

function stopText(){
   return P.not(P.eos.or(P.string('STOP'))).rep();
}

function detectStop(){
    return P.try(stop().or(stopText())).rep();
}
```

**Comment by d-plaindoux** [comment]
In order to write the correct parser the first operation consists in identifying regularities.

```
WORD SEP WORD SEP recognised by WORD (SEP WORD)* SEP?
```

Seems to be parsed by 
```
   var SEP    = P.string('STOP');
   var WORD = P.not(SEP); 
   return WORD.then(SEP.thenRight(WORD)).thenLeft(SEP.opt()).flattenDeep()
```

**Comment by nicolas-zozol** [comment]
Merci. J'arrive au code Javascript suivant qui répond exactement au problème.

import P from '../parsec/parser';
function stop(){
    return P.string('stop').rep();
}

function text(){
   return P.not(P.eos.or(P.string('stop')));
}

function read(){
    return text().rep()  .map(a=>a.join(''))   .then(stop()).optrep()   .flattenDeep()
}

function parseText( line, offset=0){
    return read().parse(stream.ofString(line), offset)
}

parseText ()  ->  [ 'test1', 'stop', 'test2', 'stop' ]

La fonction read suivante marche aussi avec des performance similaire
 function read(){
    return stop().or(text().rep().map(a=>a.join(''))).optrep();
}
