### ISSUE TITLE
Overloading

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/parsec#44]
We often use `combinator.parse(Stream.of(document) )`. We could add a function `combinator.parseString(document)`, or modify the `parse(doc | stream)` function to test if argument is a String or a Stream.

Question is the same with the extractor. Should we create `textUntil( string | combinator `), or create `textUntil(combinator)` and `textUntilString(string)` ?

**Comment by d-plaindoux** [comment]
Well since JS has no type checker may be this can be mimic by extended naming convention. But in parallel I really appreciate smart functions able to used the right adapter allowing a kind of method overloading ...

**Comment by simon-zozol** [comment]
I think that combinator.parse('some string') should work fine (duck typing)
Is this what you mean by "smart function", d-plaindoux?

**Comment by d-plaindoux** [comment]
Yes :-)

**Comment by nicolas-zozol** [comment]
Ok, we'll do this way, I prefer to.
