### ISSUE TITLE
Test `optrep` is not accorded to its text

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/parsec#6]
The question is : When you use optrep(), is it ok to have zero elements ? I think so according to the passing tests.

```
'expect (optrep) to accepted': function(test) {

    test.deepEqual(parser.char("a").optrep().parse(stream.ofString("a"),0).isAccepted(),
                   true,
                   'should be accepted.');

  },

  'expect (optrep) none to accepted': function(test) {

    test.deepEqual(parser.char("a").optrep().parse(stream.ofString("b"),0).isAccepted(),
                   true,
                   'should be rejected.');  // <===== HERE : did you meant 'Sould be accepted' ?

  },
```

I'm not fond of this semantic : in real language, you repeat when you have at least two elements. optrep() should be  ok with one element or more, but not OK with zero elements.

So we need to build something else when you need to test a real repetition (at least two elements). Something like : 

```
    P.try(anyTitle()).blankLine().blankLine().optrep().paragraph()  // at least one blankline
```

**Comment by d-plaindoux** [comment]
Well the sentence in the test is not correct. In fact you have the following operators:
- opt for zero or one
- optrep for zero or more (kleene operator)
- rep for one or more

**Comment by d-plaindoux** [comment]
For the repetition you already have a specific operator. 

```
blankline.occ(2) // for exactly two blank line occurrences
```

**Comment by nicolas-zozol** [comment]
OK, I'll change the test text. Cool for `occ()`. I keep it opened, I should not have closed it.

**Comment by d-plaindoux** [comment]
Should we change `occ` for `occurrence` Implicit (incomplete) vs. Explicit ?

**Comment by nicolas-zozol** [comment]
I'm always for explicit and long name functions. I pay IntelliJ for Ctrl+Space.
