### ISSUE TITLE
Creating an extensible LineParser class

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/parsec#9]
I want to create a class LineParser :

```
export default class LineParser {  // ideally it could extend directly Parser or ParserHelper

   textValue(chars) {
        return { text: chars.join('').trim() };
    }
    text(separator) {
        if (separator) {
                                                                /// vvvv this is null
            return P.not(eol.or(P.string(separator))).optrep().map(this.textValue);
        } else {....}
    }
```

The problem is that this fonction is extracted from the class with this code :

```
// (('b -> Parser 'a 'c) * 'b)-> Parser 'a 'c
function lazy(p, parameters) {
                                             //  vvvv 'this' will always be null :(
    return new Parser((input, index=0) => p.apply(null, parameters).parse(input, index));
}

```

Do you have any clue to avoid this `p.apply(null)`  ?

**Comment by d-plaindoux** [comment]
One solution can be applied in such situation:

```
// (('b -> Parser 'a 'c) * 'b * d?)-> Parser 'a 'c
function lazy(p, parameters,self) {
    return new Parser((input, index=0) => p.apply(self, parameters).parse(input, index));
}
```

Another solution can be applied using `bind`. It seems the fat arrow in ES6 solves this problem binding automatically this in the scope (http://www.fullstacktraining.com/articles/arrow-functions-in-es6-es2015).

**Comment by nicolas-zozol** [comment]
My bad :) At one place, I've written : `P.lazy(this.text, ["__"])` instead of `P.lazy(this.text.bind(this), ["__"])`

I would anyway recommend to bind the `p` function on itself, as I don't see why it would be bound to null :

```
function lazy(p, parameters) {
    return new Parser((input, index=0) => p.apply(p.prototype, parameters).parse(input, index));
}
```

The strange thing is that it works with `p.apply(null, params)`. I will investigate further :)

**Comment by d-plaindoux** [comment]
I agree the p.prototype usage instead of an additional parameter.

**Comment by nicolas-zozol** [comment]
I have put back the `self` parameter, or some additional tests could not pass.
